/**
 * Default structure outline sections placeholder mapping for the 3 roles
 */

export const defaultSections = {
  creator: [
    { id: 'sec-1', type: 'overview', title: 'Overview', locked: true, instruction: 'Write a comprehensive course section overview.' },
    { id: 'sec-2', type: 'outcomes', title: 'Learning Outcomes', locked: true, instruction: 'Define observable student learning outcomes.' },
    { id: 'sec-3', type: 'core_content', title: 'Core Content', locked: true, instruction: 'Draft the main instructional curriculum text.' },
    { id: 'sec-4', type: 'exercises', title: 'Exercises', locked: true, instruction: 'Build hands-on practice exercises.' },
    { id: 'sec-5', type: 'quiz', title: 'Quiz', locked: true, instruction: 'Generate multiple-choice review questions.' }
  ],
  student: [
    { id: 'sec-6', type: 'why_matters', title: 'Why This Matters', locked: true, instruction: 'Explain real-world relevance.' },
    { id: 'sec-7', type: 'journey', title: 'Learning Journey', locked: true, instruction: 'Provide structured walk through tips.' },
    { id: 'sec-8', type: 'practice', title: 'Practice Exercises', locked: true, instruction: 'Create student task items.' },
    { id: 'sec-9', type: 'debugging', title: 'Debugging Tips', locked: true, instruction: 'Common issues and error handling.' },
    { id: 'sec-10', type: 'ethics', title: 'Ethics & Best Practices', locked: true, instruction: 'Provide ethical scope and optimization standards.' }
  ],
  educator: [
    { id: 'sec-11', type: 'facilitator', title: 'Facilitator Guide', locked: true, instruction: 'Provide educator delivery outline.' },
    { id: 'sec-12', type: 'engagement', title: 'Engagement Strategies', locked: true, instruction: 'Suggest classroom interactivity plans.' },
    { id: 'sec-13', type: 'rubric', title: 'Assessment Rubric', locked: true, instruction: 'Provide tabular grading guidelines.' },
    { id: 'sec-14', type: 'assessment', title: 'Assessment Tasks', locked: true, instruction: 'Recommend assessment parameters.' },
    { id: 'sec-15', type: 'teaching_tips', title: 'Teaching Tips', locked: true, instruction: 'Instructor shortcuts.' },
    { id: 'sec-16', type: 'discussion', title: 'Discussion Questions', locked: true, instruction: 'Formulate open questions.' }
  ]
};

export const mergeSections = (lessonSections) => {
  const baseSections = JSON.parse(JSON.stringify(defaultSections));
  if (!lessonSections) return baseSections;
  
  const merged = {};
  ['creator', 'student', 'educator'].forEach(role => {
    const baseRoleSecs = baseSections[role] || [];
    const inputRoleSecs = lessonSections[role] || [];

    if (!inputRoleSecs || !inputRoleSecs.length) {
      merged[role] = baseRoleSecs;
      return;
    }

    const baseTypes = new Set(baseRoleSecs.map(b => b.type));
    const hasBaseTypesInInput = inputRoleSecs.some(i => baseTypes.has(i.type));

    if (hasBaseTypesInInput) {
      // User has configured/reordered sections. Preserve exact user order and append any missing base items.
      const processed = inputRoleSecs.map(i => {
        const match = baseRoleSecs.find(b => b.type === i.type || b.id === i.id);
        return match ? { ...match, ...i } : i;
      });
      const presentTypes = new Set(processed.map(p => p.type));
      const presentIds = new Set(processed.map(p => p.id));
      const missingBase = baseRoleSecs.filter(b => !presentTypes.has(b.type) && !presentIds.has(b.id));

      merged[role] = [...processed, ...missingBase];
    } else {
      // Input only contains custom sections generated by AI.
      // Keep standard base sections at top, followed by the custom sections.
      merged[role] = [...baseRoleSecs, ...inputRoleSecs];
    }
  });

  return merged;
};
