export const trendingTopics = [
  { category: 'Software Engineering', title: 'Advanced Cloud Architecture', desc: 'Design scalable microservices with Docker, Kubernetes, and Go.', prompt: 'Design a 4-week advanced course on Cloud-Native Microservices Architecture with Go (8 lessons, 2 per week) for senior backend engineers. Use Go (Golang), Docker, Kubernetes, and gRPC. For each lesson provide: title, learning objectives, lecture outline, hands-on coding lab, and a short quiz. Cover concurrent channel structures, distributed tracing, API gateways, circuit breakers, and container orchestration. End with a final project: deploying a resilient, concurrent multi-service backend with gRPC communication on a local Kubernetes cluster, including a rubric and submission checklist.' },
  { category: 'Artificial Intelligence', title: 'AI & Machine Learning', desc: 'Train neural networks and computer vision models using PyTorch.', prompt: 'Design a 3-week intermediate course on Deep Learning and Computer Vision (6 lessons, 2 per week) for data scientists. Use Python, PyTorch, OpenCV, and Jupyter Notebooks. For each lesson provide: title, learning objectives, lecture outline, hands-on Jupyter coding lab, and a short quiz. Cover backpropagation, convolutional neural networks (CNNs), transfer learning, and object detection frameworks like YOLO. End with a final project: building and training a custom CNN image classifier for autonomous vehicle sign recognition.' },
  { category: 'Cybersecurity', title: 'Offensive Cybersecurity', desc: 'Master penetration testing, exploit development, and network defense.', prompt: 'Design a 2-week intensive course on Offensive Cybersecurity and Penetration Testing (4 lessons) for security analysts. Use Kali Linux, Metasploit, Wireshark, and Python scripting. For each lesson provide: title, learning objectives, lecture outline, hands-on ethical hacking lab, and a short quiz. Cover network reconnaissance, vulnerability scanning, privilege escalation, and crafting custom Python exploits. End with a final project: conducting a simulated penetration test on a vulnerable lab environment and writing a professional security audit report.' },
  { category: 'Artificial Intelligence', title: 'Generative AI in Education', desc: 'Implement LLMs in classrooms safely and effectively.', prompt: 'Design a 4-week advanced course on Generative AI Integration in Modern School Education Systems (8 lessons) for school administrators and curriculum designers. Use ChatGPT, Midjourney, and LMS plugins. Cover AI ethics, prompt engineering for educators, student assessment automation, and plagiarism detection. For each lesson provide: title, learning objectives, lecture outline, hands-on lab on prompt design, and a short quiz. End with a final project: creating a fully AI-assisted school curriculum blueprint.' },
  { category: 'Data Science', title: 'Data Analysis with Pandas', desc: 'Wrangle, clean, and visualize complex datasets in Python.', prompt: 'Design a 2-week practical course on Data Analysis and Wrangling with Python Pandas (4 lessons) for business analysts. Use Python, Pandas, Matplotlib, and Jupyter. Cover data cleaning, merging dataframes, handling missing values, and time-series analysis. For each lesson provide: title, learning objectives, lecture outline, hands-on lab with real CSV datasets, and a short quiz. End with a final project: performing exploratory data analysis (EDA) on a messy financial dataset to extract actionable business insights.' },
  { category: 'Digital Transformation', title: 'Cloud Computing Migration', desc: 'Shift legacy infrastructure to AWS and Azure securely.', prompt: 'Design a 4-week enterprise course on Cloud Computing Migration Strategies (8 lessons) for IT infrastructure managers and solutions architects. Use AWS Migration Hub, Azure Migrate, and Docker. Cover on-premise assessment, lift-and-shift vs refactoring, security compliance, and cost optimization. For each lesson provide: title, learning objectives, lecture outline, hands-on lab simulating a server migration, and a short quiz. End with a final project: architecting a comprehensive migration plan for a legacy monolithic application to a highly available cloud environment.' },
  { category: 'Digital Transformation', title: 'Agile Leadership', desc: 'Modern software delivery frameworks and team dynamics.', prompt: 'Design a 2-week advanced course on Agile Project Management and Engineering Leadership (4 lessons) for engineering managers and scrum masters. Use Jira, Confluence, and Miro. Cover servant leadership, sprint planning, resolving team conflicts, and measuring velocity metrics. For each lesson provide: title, learning objectives, lecture outline, hands-on roleplay scenario lab, and a short quiz. End with a final project: developing an Agile transformation roadmap for a dysfunctional engineering team.' },
  { category: 'Education Technology', title: 'Gamified Learning Design', desc: 'Design interactive rewards and pathways for student retention.', prompt: 'Design a 3-week creative course on Gamification Design for Student Learning Systems (6 lessons) for educational technologists and UI/UX designers. Use Figma, Kahoot, and Unity (basic). Cover motivation theory, points/badges/leaderboards (PBL), narrative design, and adaptive difficulty. For each lesson provide: title, learning objectives, lecture outline, hands-on lab prototyping a gamified UI, and a short quiz. End with a final project: designing a gamified learning pathway prototype for a middle-school science app.' },
  { category: 'Software Engineering', title: 'Next.js 15 Foundations', desc: 'Server components, server actions, and layout routing.', prompt: 'Design a 2-week modern web course on Next.js 15 App Router and Server Actions Development (4 lessons) for frontend React developers. Use Next.js 15, React 19, TailwindCSS, and Vercel. Cover server components, server actions, nested layouts, data fetching, and caching strategies. For each lesson provide: title, learning objectives, lecture outline, hands-on lab building a dynamic route, and a short quiz. End with a final project: building a full-stack e-commerce storefront with server actions for cart mutations and seamless optimistic UI updates.' }
];

export const suggestedPrompts = [
  { title: 'AI Software Pipeline', desc: 'Design a 2-week intermediate course on Agentic SDLC Pipelines (4 lessons) for engineers.', prompt: 'Design a 2-week intermediate course on Agentic Software Development Life Cycle (SDLC) Pipelines (4 lessons, 2 per week) for software engineers and QA specialists interested in AI-driven automation. Use AI orchestration tools, pipeline automation frameworks, and quality metrics analysis techniques. For each lesson provide: title, learning objectives, lecture outline, hands-on lab, and a short quiz. Cover multi-agent systems, specification enrichment, continuous integration, and evaluation metrics like Cohen’s kappa. End with a final project: build an autonomous SDLC pipeline prototype using open-source AI agents, with a rubric and submission checklist.' },
  { title: 'Pediatric Gene Expression', desc: 'Design a 2-week intermediate biomedical research course (4 lessons) for researchers.', prompt: 'Design a 2-week intermediate biomedical research course on Pediatric Cellular Mapping and Gene Expression Research (4 lessons, 2 per week) for biomedical researchers and bioinformaticians. Use genomics databases, bioinformatics tools, AI analytics platforms, and data curation software. For each lesson provide: title, learning objectives, lecture outline, hands-on lab analyzing pediatric gene expression data, and a short quiz. Cover genomics, bioinformatics, data curation, AI analytics, interdisciplinary collaboration, and precision medicine. End with a final project: creating a pediatric gene expression analysis report using real datasets and AI tools, with rubric and submission checklist.' },
  { title: 'Microlearning Design', desc: 'Design a 2-week intermediate Retention-Focused Microlearning Design course (4 lessons).', prompt: 'Design a 2-week intermediate Retention-Focused Microlearning Design course (4 lessons, 2 per week) for instructional designers and L&D specialists. Use AI content generation tools like ChatGPT, adaptive learning platforms such as EdApp, and learning analytics software like Watershed. For each lesson provide: title, learning objectives, lecture outline, hands-on lab creating retrieval-based micro-lessons, and a short quiz. Cover cognitive science principles, retrieval practice, spaced repetition, adaptive scheduling, and engagement mechanics. End with a final project: develop an AI-powered microlearning module with spaced retrieval practice, including a rubric and submission checklist.' },
];
