"""create core tables

Revision ID: b5dc4be47faa
Revises: 
Create Date: 2026-08-14 10:20:23.739065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5dc4be47faa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('tech_tags', sa.Text(), nullable=False),
    sa.Column('config_lessons', sa.Integer(), nullable=False),
    sa.Column('config_duration', sa.Integer(), nullable=False),
    sa.Column('config_difficulty', sa.String(length=30), nullable=False),
    sa.Column('config_audience', sa.String(length=100), nullable=False),
    sa.Column('subject_context', sa.Text(), nullable=False),
    sa.Column('prerequisites', sa.Text(), nullable=False),
    sa.Column('boundaries', sa.Text(), nullable=False),
    sa.Column('learning_outcomes', sa.Text(), nullable=False),
    sa.Column('proposals', sa.Text(), nullable=False),
    sa.Column('selected_proposal_id', sa.Integer(), nullable=True),
    sa.Column('structure', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('section_type', sa.String(length=50), nullable=True),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_session_id'), 'history', ['session_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_lesson_id'), 'sections', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_lesson_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_history_session_id'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('sessions')
    op.drop_table('courses')
    # ### end Alembic commands ###
